name: Uppdatera Fotbollskalender

on:
  schedule:
    - cron: '0 3 * * *' # Körs automatiskt varje natt kl 03:00
  push:
    branches: [ main ] # Körs varje gång du sparar ändringar på GitHub
  workflow_dispatch: # Gör att du kan starta körningen manuellt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut kod
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installera bibliotek
        run: |
          pip install requests beautifulsoup4 icalendar

      - name: Generera kalenderfil
        run: python generator.py

      - name: Ladda upp till One.com via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './kalender.ics'
          remote_path: 'httpd.www/fchp/' # Borttaget inledande / för att matcha One.coms rättigheter
          sftp_only: true # Tvingar SFTP-protokollet
          delete_remote_files: false
