name: Hitta Webbmappen

on:
  workflow_dispatch:

jobs:
  locate:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut kod
        uses: actions/checkout@v3

      - name: Generera fil
        run: |
          pip install requests beautifulsoup4 icalendar
          python generator.py

      - name: Lista ALLA mappar på servern
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './kalender.ics'
          remote_path: './'
          sftp_only: true
          # Detta kommando listar dolda mappar för att hitta 'www' eller 'httpd.www'
          args: '-la'
