name: Uppdatera Kalender via SFTP

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installera paket
        run: pip install requests beautifulsoup4 icalendar

      - name: Generera ICS-fil
        run: python generator.py

      - name: Ladda upp via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: '' # Lämna tom om du använder lösenord
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './kalender.ics' # Vi skickar bara själva filen
          remote_path: '/httpd.www/' # Detta är standardmappen hos One.com
          port: 22
