name: Uppdatera Fotbollskalender

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut kod
        uses: actions/checkout@v3

      - name: Installera Python och generera fil
        run: |
          pip install requests beautifulsoup4 icalendar
          python generator.py

      - name: Ladda upp till den publika mappen
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './kalender.ics'
          # Vi provar nu den absoluta stigen till din webbmapp
          remote_path: '/elvaett.se/fchp/'
          sftp_only: true
